# Generated by Django 4.2.13 on 2026-05-14 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=150)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('exchange', models.CharField(default='NASDAQ', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(choices=[('stock_ingestion', 'Stock Price Ingestion'), ('macro_indicators', 'Macro Indicators Ingestion'), ('dbt_transform', 'dbt Transformation')], max_length=100)),
                ('run_id', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_ingested', models.IntegerField(default=0)),
                ('records_transformed', models.IntegerField(default=0)),
                ('tickers_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VolatilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('rolling_vol_30d', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('rolling_vol_90d', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('annualized_vol', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('beta', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('sharpe_30d', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('adj_close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='yfinance', max_length=50)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='pipeline_st_ticker_5c36e2_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(null=True)),
                ('daily_return', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('ma_7d', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ma_30d', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ma_90d', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='pipeline_st_ticker_6a1b5e_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectorAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('avg_return', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('avg_volatility', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('total_volume', models.BigIntegerField(null=True)),
                ('num_stocks', models.IntegerField(default=0)),
                ('top_performer', models.CharField(blank=True, max_length=10)),
                ('bottom_performer', models.CharField(blank=True, max_length=10)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', 'sector'],
                'unique_together': {('sector', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(default='monthly', max_length=20)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='FRED', max_length=50)),
            ],
            options={
                'ordering': ['-date', 'series_id'],
                'indexes': [models.Index(fields=['series_id', 'date'], name='pipeline_ma_series__a63ba7_idx')],
                'unique_together': {('series_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DbtTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_name', models.CharField(max_length=200)),
                ('test_name', models.CharField(max_length=200)),
                ('test_type', models.CharField(default='generic', max_length=50)),
                ('column_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warn', 'Warn')], max_length=10)),
                ('failures', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('pipeline_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dbt_tests', to='pipeline.pipelinerun')),
            ],
            options={
                'ordering': ['-run_at', 'model_name'],
                'indexes': [models.Index(fields=['run_at', 'status'], name='pipeline_db_run_at_d94c10_idx'), models.Index(fields=['model_name'], name='pipeline_db_model_n_ab3e71_idx')],
            },
        ),
    ]
